### PR TITLE
close Engine Output dialog if Escape is pressed

### PR DESCRIPTION
**Pull request by SpiritQuaddicted**
This is probably not done well

### CODE REVIEW

**Comment by hkBattousai** [comment]
The output console should have been optional. It could be hidden or disabled by default, and could be enabled from the settings. An ordinary user would never bother reading the output messages. It is just to bothersome to close it EVERY TIME after finishing a map!!...

**Comment by SpiritQuaddicted** [comment]
If it bothers you SO much, comment out https://github.com/hrehfeld/QuakeInjector/blob/5db925b8ca8205260849704c78240926be053fec/src/de/haukerehfeld/quakeinjector/PackageInteractionPanel.java#L486 and rebuild it. You should need nothing but the JDK and Eclipse for this.

**Comment by hrehfeld** [comment]
@SpiritQuaddicted can you move it somewhere sensible? :-)

**Comment by SpiritQuaddicted** [comment]
Too abstract for me, I wouldn't know how. :\

**Pull request merged**
