### PR TITLE
Gradle Conversion + EXE Build

### PR DESCRIPTION
**Pull request by jjelliott**
This converts the project to use Gradle instead of Ant as its build tool. This tool is overall simpler while being more powerful.

This also includes a custom command to build a distribution for Windows, using `gradlew.bat winDist` on Windows or `./gradlew winDist` on Unix. This distribution is an EXE and includes a runtime so it will work on systems without Java.

Feel free to ask any questions.

### CODE REVIEW

**Comment by jjelliott** [comment]
Converted back to draft due to a settings issue. Will change back once I fix/verify.

**Comment by SpiritQuaddicted** [comment]
Thank you so much, this is a huge step for the Quake Injector and something people have been wishing for since ... always!

Sorry I merged another PR before this, would have been cleaner the other way around. :\

Some wishes but please educate me if they are stupid :D
- It would be great to always use the latest gradle version instead of hard-coding 6.5.1
- Same for the Java version, maybe always the latest LTS version?
- `build.xml` can probably be removed as it is from ant too, right?
- Could you name the `QuakeInjector-exe.zip` something like `QuakeInjector.exe-{gittag}-{shortcommithash}.zip`?
- There is one deprecation warning for gradle 6.5.1 already: `destinationDir` -> `destinationDirectory`

**Comment by jjelliott** [comment]
It's fine, I'll rebase it so it's a clean merge.

As for the questions:

- If you install Gradle on your machine you can use your local copy instead and use any version you wish. As for the committed version, it needs to be hardcoded due to the way the wrapper works, but I can go ahead and make it the newest. It just picked up the version off of my system copy.
- It assumes code is Java 8 compatible right now. If there is a need for new features, that can be changed with the `sourceCompatibility` and `targetCompatibility` fields. Best practice is to use the lowest possible version, though, because it's more likely to be compatible with X user's system.
- build.xml can be removed, I just missed it on the clearing phase. 
- Version number should be able to be added pretty easily. I'll do that tonight. 
- The deprecated line can actually probably be removed. It looks like it might just be specifying the default unnecessarily. I'll test that when I add the version numbers.

**Comment by jjelliott** [comment]
The newest version of Gradle is emitting a deprecation warning for a repository that isn't actually being used. I'm not sure why it's being printed, but it's fine because nothing is actually using it.

**Comment by jjelliott** [comment]
Upgraded to Gradle 7.1.1, and the requested improvements are complete.

**Comment by SpiritQuaddicted** [comment]
You're the 
```
   *               (     
 (  `              )\ )  
 )\))(    (   (   (()/(  
((_)()\   )\  )\   /(_)) 
(_()((_) ((_)((_) (_))   
|  \/  | \ \ / /  | _ \  
| |\/| |  \ V /   |  _/  
|_|  |_|   \_/    |_|    
                         
```
!!

This is something that people have been longing for ever since the first release. It was a constant source of pain, confusion and anger to have to fiddle with Java on Windows. Now people can just unzip and get fragging.

Thank you!

**Pull request merged**
